version: '3.6'
services: 
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: hbase2_zk
    expose:
      - "2181"
    logging:
        driver: "none"
    privileged: true                                 # 拥有容器内命令执行的权限
    networks:                                        # docker 网络设置
        hbase2-network:
            ipv4_address: 172.37.0.2

  hbase:
    image: neuw84/hbase-2.0.2-standalone
    container_name: hbase2.0.2
    links:
      - zookeeper
    logging:
      driver: "none"
    privileged: true                                 # 拥有容器内命令执行的权限
    networks:                                        # docker 网络设置
        hbase2-network:
            ipv4_address: 172.37.0.3
    ports:
      - "16010:16010"
    expose:
      - "8080"
      - "9090"
      - "16000"
      - "16010"
      - "16020"
      - "16030"
    command: ["/wait-for-it.sh", "zookeeper:2181", "-t", "10", "--", "/usr/bin/supervisord"]

networks:
  hbase2-network:
     driver: bridge
     ipam:
       driver: default
       config:
          - 
            subnet: 172.37.0.0/16
