version: '3'
services: 
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: hbase2_zk
    expose:
      - "2181"
    logging:
        driver: "none"

  hbase:
    image: neuw84/hbase-2.0.2-standalone
    container_name: hbase2.0.2
    links:
      - zookeeper
    logging:
      driver: "none"
    ports:
      - "16010:16010"
    expose:
      - "8080"
      - "9090"
      - "16000"
      - "16010"
      - "16020"
      - "16030"
    command: ["/wait-for-it.sh", "zookeeper:2181", "-t", "10", "--", "/usr/bin/supervisord"]
